// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("AsynkronIT")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2013-2016 AsynkronIT")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("0.9.0.0")]
[assembly: AssemblyFileVersionAttribute("0.9.0.0")]
